# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from admin3 import Ui_Dialog3
import psycopg2
p=open("admin.txt","r")
x=p.read()
p.close()
company_id=int(x)
class Ui_Dialog2(object):
    def move_to_admin3(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_Dialog3()
        self.ui.setupUi(self.window)
        self.window.show()
    def sort_display(self):
        x=self.comboBox.currentIndex()
        if(x==0):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute("select admin_sort_id(%s);",[company_id])
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
        elif(x==1):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute("select admin_sort_food(%s);",[company_id])
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
            
        elif(x==2):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute("select admin_sort_travel(%s);",[company_id])
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
    
    def insert_new(self):
        a=int(self.lineEdit.text())
        conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
        cur = conn.cursor()
        cur.execute("select * from path where path_id=(%s)",[a])
        x=cur.fetchall()
        print(x)
        print(len(x))
        
        if(len(x)!=0):
            self.lineEdit.clear()
        else:
            b=self.lineEdit_2.text()
            c=self.lineEdit_3.text()
            d=self.lineEdit_4.text()
            e=self.lineEdit_5.text()
            f=int(self.lineEdit_6.text())
            g=int(self.lineEdit_7.text())
            cur.execute("select company_name from company where id=(%s)",[company_id])
            x=cur.fetchall()
            name=x[0]
            cur.execute("insert into path values(%s,%s,%s,%s,%s,%s,%s,%s,%s)",(a,b,c,d,e,name,f,g,company_id))
            conn.commit()
            conn.close()
         
    def update_new(self):
        x=self.comboBox_2.currentIndex()
        if(x==0):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            a=int(self.lineEdit_9.text())
            b=self.lineEdit_8.text()
            cur.execute("update path set startpoint=(%s) where path_id=(%s)",(b,a))
            conn.commit()
            conn.close()
        elif(x==1):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            a=int(self.lineEdit_9.text())
            b=self.lineEdit_8.text()
            cur.execute("update path set endpoint=(%s) where path_id=(%s)",(b,a))
            conn.commit()
            conn.close()
        elif(x==2):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            a=int(self.lineEdit_9.text())
            b=self.lineEdit_8.text()
            cur.execute("update path set via=(%s) where path_id=(%s)",(b,a))
            conn.commit()
            conn.close()
        elif(x==3):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            a=int(self.lineEdit_9.text())
            b=self.lineEdit_8.text()
            cur.execute("update path set up_down=(%s) where path_id=(%s)",(b,a))
            conn.commit()
            conn.close()
        elif(x==4):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            a=int(self.lineEdit_9.text())
            b=int(self.lineEdit_8.text())
            cur.execute("update path set travelcost=(%s) where path_id=(%s)",(b,a))
            conn.commit()
            conn.close()
        elif(x==5):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            a=int(self.lineEdit_9.text())
            b=int(self.lineEdit_8.text())
            cur.execute("update path set foodcost_id=(%s) where path_id=(%s)",(b,a))
            conn.commit()
            conn.close()
    def delete_new(self):
        x=int(self.lineEdit_10.text())
        conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
        cur = conn.cursor()
        cur.execute("delete from path where path_id=(%s)",[x])
        conn.commit()
        conn.close()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(932, 801)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 110, 931, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(40, 730, 151, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.insert_new)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 730, 191, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.update_new)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 730, 211, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.delete_new)
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(600, 30, 171, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.move_to_admin3)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(40, 40, 191, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 40, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.sort_display)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 470, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 500, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 530, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 570, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 610, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(0, 650, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 690, 81, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 470, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 500, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 530, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 570, 113, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 610, 113, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 650, 113, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 690, 113, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(370, 620, 151, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit_8 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_8.setGeometry(QtCore.QRect(370, 680, 161, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(370, 520, 211, 20))
        self.label_8.setObjectName("label_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_9.setGeometry(QtCore.QRect(370, 560, 113, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(690, 630, 211, 20))
        self.label_9.setObjectName("label_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_10.setGeometry(QtCore.QRect(690, 680, 113, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "14"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "15"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "17"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "18"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "19"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "20"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "From"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "To"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "via"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "up/down"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "cost of travel"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Cost of food"))
        self.pushButton.setText(_translate("Dialog", "Insert"))
        self.pushButton_2.setText(_translate("Dialog", "Update"))
        self.pushButton_3.setText(_translate("Dialog", "Delete"))
        self.pushButton_6.setText(_translate("Dialog", "View your order"))
        self.comboBox.setItemText(0, _translate("Dialog", "sort by id"))
        self.comboBox.setItemText(1, _translate("Dialog", "sort by cost of food"))
        self.comboBox.setItemText(2, _translate("Dialog", "sort by cost of travel"))
        self.pushButton_4.setText(_translate("Dialog", "OK"))
        self.label.setText(_translate("Dialog", "id:"))
        self.label_2.setText(_translate("Dialog", "From :"))
        self.label_3.setText(_translate("Dialog", "To :"))
        self.label_4.setText(_translate("Dialog", "Via :"))
        self.label_5.setText(_translate("Dialog", "Up/down :"))
        self.label_6.setText(_translate("Dialog", "cost of travel :"))
        self.label_7.setText(_translate("Dialog", "cost of food :"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "From"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "To"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "via"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "up/down"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "cost of travel"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "cost of food"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the Id to be updated</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the Id to be Deleted : </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog2()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

