# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import psycopg2
p=open("admin.txt","r")
x=p.read()
p.close()
company_id=x
#company_id=2
class Ui_Dialog3(object):
    def sort_view(self):
        x=self.comboBox.currentIndex()
        if(x==0):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute("select * from view where company_id=(%s) order by total_cost_travel",[company_id])
            rows = cur.fetchall()
            self.tableWidget.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
        elif(x==1):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute("select * from view where company_id=(%s) order by total_cost_food",[company_id])
            rows = cur.fetchall()
            self.tableWidget.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
        elif(x==2):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute("select * from view where company_id=(%s) order by no_bus",[company_id])
            rows = cur.fetchall()
            self.tableWidget.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1359, 622)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 60, 1361, 561))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setRowCount(18)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(370, 20, 161, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.sort_view)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(180, 20, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "14"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "15"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "18"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "19"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "20"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Names"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Number"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "hotel cost"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "path1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "path2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "path3"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "hotel1"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "hotel2"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "hotel3"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "bus type"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "No of bus"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "total cost for travel"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Dialog", "total cost for food"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("Dialog", "No of student"))
        
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.comboBox.setItemText(0, _translate("Dialog", "sort by travel cost"))
        self.comboBox.setItemText(1, _translate("Dialog", "sort by food cost"))
        self.comboBox.setItemText(2, _translate("Dialog", "sort by bus"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog3()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

