# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from user4 import Ui_Dialog4
from user5 import  Ui_Dialog5
import psycopg2

f=open("user2.txt","r")
x=f.read()
y=x.split(" ")
path_id=int(y[0])
f.close()

f=open("user1.txt","r")
x=f.read()
y=x.split(" ")
no_student=int(y[4])
f.close()
hotel1_id=0

class Ui_Dialog3(object):
    def move_to_user4(self):
        hotel1_id=int(self.lineEdit.text())
        f=open("user3.txt","w")
        f.write(" ".join([str(hotel1_id)]))
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_Dialog4()
        self.ui.setupUi(self.window)
        self.window.show()
    def sort_hotel(self):
        self.type=self.comboBox.currentIndex()
        print(self.type)
        if(self.type==2):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute('select rate_dese(%s,%s);',(path_id,no_student))
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
                    
        elif(self.type==3):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute('select rate_ace(%s,%s);',(path_id,no_student))
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
        elif(self.type==0):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute('select cost_dese(%s,%s);',(path_id,no_student))
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
        elif(self.type==1):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute('select cost_asc(%s,%s);',(path_id,no_student))
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
                    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1007, 657)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 71, 951, 501))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(29)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 231, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(310, 591, 191, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(160, 599, 161, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(540, 30, 93, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.sort_hotel)
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(650, 600, 321, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.move_to_user4)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(380, 30, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "18"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "20"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("Dialog", "21"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("Dialog", "22"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("Dialog", "23"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("Dialog", "24"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("Dialog", "25"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("Dialog", "26"))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("Dialog", "27"))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("Dialog", "28"))
        item = self.tableWidget.verticalHeaderItem(27)
        item.setText(_translate("Dialog", "29"))
        item = self.tableWidget.verticalHeaderItem(28)
        item.setText(_translate("Dialog", "30"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hotel id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Address"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Hotel Star rating"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Rating"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "pageurl"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "room count"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "count per room"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Room type"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "hotal Name"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "Path Id"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "cost"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic; text-decoration: underline;\">Way to Destination :</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the Hotel id:</span></p></body></html>"))
        self.pushButton_5.setText(_translate("Dialog", "Move to Next"))
        self.comboBox.setItemText(0, _translate("Dialog", "sort by cost(desc)"))
        self.comboBox.setItemText(1, _translate("Dialog", "sort by cost(asce)"))
        self.comboBox.setItemText(2, _translate("Dialog", "sort by rate(desc)"))
        self.comboBox.setItemText(3, _translate("Dialog", "sort by rate(aces)"))
        self.pushButton.setText(_translate("Dialog", "ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog3()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

