# -*- coding: utf-8 -*-
"""
Created on Sun Apr 15 15:06:48 2018

@author: Nivedh Auswin
"""

from PyQt5 import QtCore, QtGui, QtWidgets
import psycopg2
from user3 import Ui_Dialog3

path1_id=0
no_bus=0
bus_type=" "

class Ui_Dialog2(object):
    def print_table(self):
        x=self.lineEdit_2.text()
        if(x=='d'):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute("select path_to_desti();")
            c = conn.cursor('cursor2')
            rows = c.fetchall()
            self.tableWidget.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
        else:
            y=int(self.lineEdit_2.text())
            print(y)
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute("select companyid from path where path_id=(%s)",[y])
            rows = cur.fetchall() 
            y=rows[0][0]
            cur.execute("select no_bus(%s);",[y])
            c = conn.cursor('cursor2')
            rows = c.fetchall() 
            self.tableWidget_2.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget_2.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget_2.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
                    conn.close()
           
    def move_to_user3(self):
        path1_id=int(self.lineEdit_2.text())
        no_bus=int(self.lineEdit_2.text())
        bus_type=self.comboBox.currentText()
        
        f=open("user2.txt","w")
        f.write(" ".join([str(i) for i in [path1_id,no_bus,bus_type]]))
        f.close()
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_Dialog3()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(848, 451)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(30, 50, 551, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(27)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(610, 30, 191, 91))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(610, 100, 191, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(610, 150, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.print_table)
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 260, 831, 91))
        self.tableWidget_2.setObjectName("tableWidget_2")
        
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 121, 31))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(40, 380, 171, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 380, 301, 41))
        self.pushButton_2.setStyleSheet("font: 75 11pt \"Yu Gothic UI Semilight\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.move_to_user3)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(360, 380, 113, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(260, 370, 111, 51))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "15"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "17"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "18"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "20"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "21"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "22"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("Dialog", "23"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("Dialog", "24"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("Dialog", "25"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("Dialog", "26"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("Dialog", "27"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("Dialog", "28"))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("Dialog", "29"))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("Dialog", "30"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "From"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "To"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Via"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Company"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Cost of travel"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Cost of Food"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Enter Id of Path :</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Done"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Company name"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "No of  A/C+semi AVL"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "No of A/C AVL"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "No of semi AVL"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "No of Normal AVL"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "No of students per bus"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Rating /10"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">For desination</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Dialog", "A/C+semi"))
        self.comboBox.setItemText(1, _translate("Dialog", "A/C_Only"))
        self.comboBox.setItemText(2, _translate("Dialog", "Semi_Only"))
        self.comboBox.setItemText(3, _translate("Dialog", "Normal"))
        self.pushButton_2.setText(_translate("Dialog", "Confirm Your Bus and Desti path"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">No of Bus : </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog2()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
