# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user4.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import psycopg2
from user5 import  Ui_Dialog5
f=open("user2.txt","r")
x=f.read()
y=x.split(" ")
pathid=int(y[0])
f.close()
conn = psycopg2.connect(database = "postgres", user="postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
cur = conn.cursor()
cur.execute("select companyid from path where path_id=(%s)",[pathid])
x=cur.fetchall()
conn.close()
company_id=int(x[0][0])

f=open("user1.txt","r")
x=f.read()
y=x.split(" ")
no_student=int(y[4])
f.close()

path2_id=0
path3_id=0
hotel2_id=0
hotel3_id=0
class Ui_Dialog4(object):
    def move_to_user5(self):
        path2_id=self.path1_id
        path3_id=self.path2_id
        hotel=(self.lineEdit.text()).split(',')
        hotel2_id=int(hotel[0])
        hotel3_id=int(hotel[1])
        f=open("user4.txt","w")
        f.write(" ".join([str(i) for i in [path2_id,path3_id,hotel2_id,hotel3_id,company_id]]))
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_Dialog5()
        self.ui.setupUi(self.window)
        self.window.show()
    def print_bus(self):
        self.path_id=self.lineEdit_2.text()
        if(self.path_id=='d'):   
           conn = psycopg2.connect(database = "postgres", user="postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
           cur = conn.cursor()
           cur.execute("select return_path(%s);",[company_id])
           c = conn.cursor('cursor1')
           rows = c.fetchall()
           self.tableWidget.setRowCount(0)
           for rownumber ,row_data in enumerate(rows):
               self.tableWidget.insertRow(rownumber)
               for columnnumber ,data in enumerate(row_data):
                   self.tableWidget.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
           conn.close()
        
        else:
            
            self.path_id=self.lineEdit_2.text()
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            self.path1_id=0
            self.path2_id=0
            x=(self.path_id).split(',')
            if(len(x)==1):
                self.path1_id=int(self.path_id)
            else:
                self.path1_id=int(x[0])
                self.path2_id=int(x[1])
            
            cur.execute('select return_hotel(%s,%s,%s);',(self.path1_id,self.path2_id,no_student))
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget_2.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget_2.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget_2.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
            conn.close()
    def sort_hotel(self):
        self.sort_type=self.comboBox.currentIndex()
        if(self.sort_type==0):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute('select return_hotel(%s,%s,%s);',(self.path1_id,self.path2_id,no_student))
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget_2.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget_2.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget_2.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
            conn.close()
        elif(self.sort_hotel==1):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute('select return_hotel(%s,%s,%s);',(self.path1_id,self.path2_id,no_student))
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget_2.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget_2.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget_2.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
            conn.close()
            
        elif(self.sort_hotel==3):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute('select return_hotel(%s,%s,%s);',(self.path1_id,self.path2_idno_student))
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget_2.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget_2.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget_2.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
            conn.close()
            
        elif(self.sort_hotel==3):
            conn = psycopg2.connect(database = "postgres", user = "postgres", password = "fuckoff13", host = "127.0.0.1", port = "5432")
            cur = conn.cursor()
            cur.execute('select return_hotel(%s,%s,%s);',(self.path1_id,self.path2_id,no_student))
            c = conn.cursor('cursor1')
            rows = c.fetchall()
            self.tableWidget_2.setRowCount(0)
            for rownumber ,row_data in enumerate(rows):
                self.tableWidget_2.insertRow(rownumber)
                for columnnumber ,data in enumerate(row_data):
                    self.tableWidget_2.setItem(rownumber,columnnumber,QtWidgets.QTableWidgetItem(str(data)))                
            conn.close()
            
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1050, 681)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 571, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(27)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(670, 220, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(340, 620, 191, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(190, 620, 161, 31))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(630, 20, 131, 41))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(780, 20, 211, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(780, 80, 171, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.print_bus)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 220, 93, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.sort_hotel)
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(680, 610, 321, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.move_to_user5)
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 250, 1051, 331))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(11)
        self.tableWidget_2.setRowCount(29)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "15"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "17"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "18"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "20"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "21"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "22"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("Dialog", "23"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("Dialog", "24"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("Dialog", "25"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("Dialog", "26"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("Dialog", "27"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("Dialog", "28"))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("Dialog", "29"))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("Dialog", "30"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "From"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "To"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Via"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Cost of travel"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Cost of Food"))
        
        self.comboBox.setItemText(0, _translate("Dialog", "sort by cost(desc)"))
        self.comboBox.setItemText(1, _translate("Dialog", "sort by cost(asce)"))
        self.comboBox.setItemText(2, _translate("Dialog", "sort by rate(desc)"))
        self.comboBox.setItemText(3, _translate("Dialog", "sort by rate(aces)"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the Hotel id:</span></p></body></html>"))
        self.pushButton_5.setText(_translate("Dialog", "Move to Next"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the path id</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Done"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "14"))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "15"))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget_2.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "17"))
        item = self.tableWidget_2.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "18"))
        item = self.tableWidget_2.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "20"))
        item = self.tableWidget_2.verticalHeaderItem(19)
        item.setText(_translate("Dialog", "21"))
        item = self.tableWidget_2.verticalHeaderItem(20)
        item.setText(_translate("Dialog", "22"))
        item = self.tableWidget_2.verticalHeaderItem(21)
        item.setText(_translate("Dialog", "23"))
        item = self.tableWidget_2.verticalHeaderItem(22)
        item.setText(_translate("Dialog", "24"))
        item = self.tableWidget_2.verticalHeaderItem(23)
        item.setText(_translate("Dialog", "25"))
        item = self.tableWidget_2.verticalHeaderItem(24)
        item.setText(_translate("Dialog", "26"))
        item = self.tableWidget_2.verticalHeaderItem(25)
        item.setText(_translate("Dialog", "27"))
        item = self.tableWidget_2.verticalHeaderItem(26)
        item.setText(_translate("Dialog", "28"))
        item = self.tableWidget_2.verticalHeaderItem(27)
        item.setText(_translate("Dialog", "29"))
        item = self.tableWidget_2.verticalHeaderItem(28)
        item.setText(_translate("Dialog", "30"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Hotel id"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Address"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Hotel Star rating"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Rating"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "URL"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Room count"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "count per room"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Room type"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Hotel name"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "Path Id"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "cost"))
        self.pushButton_2.setText(_translate("Dialog", "ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog4()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

